import pytest
from unittest.mock import AsyncMock, MagicMock
from app.agents.collector import Collector
from app.agents.base import AgentResult
from app.llm.base import LLMResponse


@pytest.fixture
def mock_llm():
    adapter = MagicMock()
    adapter.chat = AsyncMock()
    return adapter


@pytest.mark.asyncio
async def test_collector_returns_raw_data(mock_llm):
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["douyin features"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    result = await collector.run({"target": "douyin", "dimension": "features"})

    assert result.success is True
    assert "data_id" in result.output or "content" in result.output


@pytest.mark.asyncio
async def test_collector_with_llm_strategy(mock_llm):
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["kuaishou AI recommendation"], "target_urls": ["https://example.com"], "strategy": "web_search"}',
        model="test",
    )

    result = await collector.run({"target": "kuaishou", "dimension": "AI recommendation"})

    assert result.success is True
    assert len(result.sources) >= 0


@pytest.mark.asyncio
async def test_collector_fallback_on_parse_error(mock_llm):
    """On LLM JSON parse failure, collector falls back to simple strategy."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(content="INVALID JSON {{{", model="test")

    result = await collector.run({"target": "competitorX", "dimension": "features"})

    assert result.success is True


@pytest.mark.asyncio
async def test_collector_requires_llm_adapter():
    """Collector needs an LLM adapter to generate search strategy."""
    collector = Collector("Collector", None)

    result = await collector.run({"target": "test competitor", "dimension": "features"})

    # Without LLM, collector cannot generate strategy — this is expected behavior
    assert result.success is False
    assert "no LLM adapter" in result.error_message


@pytest.mark.asyncio
async def test_collector_injects_domain_into_system_prompt(mock_llm):
    """Domain is injected into SYSTEM_PROMPT as site:{domain} constraint."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["feishu doc"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    await collector.run({"target": "feishu", "dimension": "docs", "domain": "feishu.cn"})

    # Verify chat was called
    assert mock_llm.chat.await_count >= 1
    # Verify the system prompt used contains the domain
    call_kwargs = mock_llm.chat.call_args
    if call_kwargs is not None:
        messages = call_kwargs[0][0] if call_kwargs[0] else []
        system_message = messages[0].content if messages else ""
        assert "site:feishu.cn" in system_message


@pytest.mark.asyncio
async def test_collector_injects_domain_hint_into_user_message(mock_llm):
    """Domain hint appears in user message as site:{domain}."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["feishu doc"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    await collector.run({"target": "feishu", "dimension": "docs", "domain": "feishu.cn"})

    assert mock_llm.chat.await_count >= 1
    call_kwargs = mock_llm.chat.call_args
    if call_kwargs is not None:
        messages = call_kwargs[0][0] if call_kwargs[0] else []
        user_message = messages[1].content if len(messages) > 1 else ""
        assert "site:feishu.cn" in user_message


@pytest.mark.asyncio
async def test_collector_works_without_domain(mock_llm):
    """Collector works normally when domain is not provided."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["douyin features"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    result = await collector.run({"target": "douyin", "dimension": "features"})

    assert result.success is True


@pytest.mark.asyncio
async def test_collector_search_query_includes_site_constraint(mock_llm):
    """Search queries generated by LLM should include site:{domain} when domain is provided."""
    collector = Collector("Collector", mock_llm)
    # Use compact JSON without extra whitespace to avoid parse issues
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries":["site:feishu.cn doc","site:feishu.cn help"],"target_urls":[],"strategy":"web_search"}',
        model="test",
    )

    result = await collector.run({"target": "feishu", "dimension": "documentation", "domain": "feishu.cn"})

    assert result.success is True