import pytest
from unittest.mock import AsyncMock, MagicMock, patch
from app.agents.collector import Collector
from app.agents.base import AgentResult
from app.llm.base import LLMResponse


@pytest.fixture
def mock_llm():
    adapter = MagicMock()
    adapter.chat = AsyncMock()
    return adapter


@pytest.mark.asyncio
async def test_collector_returns_raw_data(mock_llm):
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["douyin features"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    result = await collector.run({"target": "douyin", "dimension": "features"})

    assert result.success is True
    assert "data_id" in result.output or "content" in result.output


@pytest.mark.asyncio
async def test_collector_with_llm_strategy(mock_llm):
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["kuaishou AI recommendation"], "target_urls": ["https://example.com"], "strategy": "web_search"}',
        model="test",
    )

    result = await collector.run({"target": "kuaishou", "dimension": "AI recommendation"})

    assert result.success is True
    assert len(result.sources) >= 0


@pytest.mark.asyncio
async def test_collector_fallback_on_parse_error(mock_llm):
    """On LLM JSON parse failure, collector falls back to simple strategy."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(content="INVALID JSON {{{", model="test")

    result = await collector.run({"target": "competitorX", "dimension": "features"})

    assert result.success is True


@pytest.mark.asyncio
async def test_collector_requires_llm_adapter():
    """Collector needs an LLM adapter to generate search strategy."""
    collector = Collector("Collector", None)

    result = await collector.run({"target": "test competitor", "dimension": "features"})

    # Without LLM, collector cannot generate strategy — this is expected behavior
    assert result.success is False
    assert "no LLM adapter" in result.error_message


@pytest.mark.asyncio
async def test_collector_injects_domain_into_system_prompt(mock_llm):
    """Domain is injected into SYSTEM_PROMPT as site:{domain} constraint."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["feishu doc"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    await collector.run({"target": "feishu", "dimension": "docs", "domain": "feishu.cn"})

    # Verify chat was called
    assert mock_llm.chat.await_count >= 1
    # Verify the system prompt used contains the domain
    call_kwargs = mock_llm.chat.call_args
    if call_kwargs is not None:
        messages = call_kwargs[0][0] if call_kwargs[0] else []
        system_message = messages[0].content if messages else ""
        assert "site:feishu.cn" in system_message


@pytest.mark.asyncio
async def test_collector_injects_domain_hint_into_user_message(mock_llm):
    """Domain hint appears in user message as site:{domain}."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["feishu doc"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    await collector.run({"target": "feishu", "dimension": "docs", "domain": "feishu.cn"})

    assert mock_llm.chat.await_count >= 1
    call_kwargs = mock_llm.chat.call_args
    if call_kwargs is not None:
        messages = call_kwargs[0][0] if call_kwargs[0] else []
        user_message = messages[1].content if len(messages) > 1 else ""
        assert "site:feishu.cn" in user_message


@pytest.mark.asyncio
async def test_collector_works_without_domain(mock_llm):
    """Collector works normally when domain is not provided."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["douyin features"], "target_urls": [], "strategy": "web_search"}',
        model="test",
    )

    result = await collector.run({"target": "douyin", "dimension": "features"})

    assert result.success is True


@pytest.mark.asyncio
async def test_collector_search_query_includes_site_constraint(mock_llm):
    """Search queries generated by LLM should include site:{domain} when domain is provided."""
    collector = Collector("Collector", mock_llm)
    # Use compact JSON without extra whitespace to avoid parse issues
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries":["site:feishu.cn doc","site:feishu.cn help"],"target_urls":[],"strategy":"web_search"}',
        model="test",
    )

    result = await collector.run({"target": "feishu", "dimension": "documentation", "domain": "feishu.cn"})

    assert result.success is True


@pytest.mark.asyncio
async def test_collector_search_uses_anysearch_api(mock_llm):
    """Collector calls AnySearch REST API via httpx."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["feishu features"]}',
        model="test",
    )

    # Mock httpx to verify API call
    with patch("app.agents.collector.httpx.AsyncClient") as mock_client_class:
        mock_client = AsyncMock()
        mock_client_class.return_value.__aenter__.return_value = mock_client

        # AnySearch 返回结构: {"code": 0, "message": "success", "data": {"results": [...]}}
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "code": 0,
            "message": "success",
            "data": {
                "results": [
                    {
                        "url": "https://www.feishu.cn/",
                        "description": "飞书官方网站",
                        "content": "飞书完整内容...",
                        "title": "飞书官网"
                    }
                ]
            }
        }
        mock_client.post.return_value = mock_response

        result = await collector.run({"target": "feishu", "dimension": "features"})

        # Verify post was called with correct endpoint
        assert mock_client.post.called
        first_call = mock_client.post.call_args_list[0]
        assert "api.anysearch.com/v1/search" in str(first_call)

        # Verify result success and sources were populated
        assert result.success is True
        assert result.sources


@pytest.mark.asyncio
async def test_collector_uses_search_content_when_fetch_fails(mock_llm):
    """When direct HTTP fetch fails, Collector uses content from search results."""
    collector = Collector("Collector", mock_llm)
    mock_llm.chat.return_value = LLMResponse(
        content='{"search_queries": ["feishu"]}',
        model="test",
    )

    with patch("app.agents.collector.httpx.AsyncClient") as mock_client_class:
        mock_client = AsyncMock()
        mock_client_class.return_value.__aenter__.return_value = mock_client

        # AnySearch 返回结构: {"code": 0, "message": "success", "data": {"results": [...]}}
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "code": 0,
            "message": "success",
            "data": {
                "results": [
                    {
                        "url": "https://www.feishu.cn/",
                        "description": "飞书官网",
                        "content": "飞书完整正文内容 from search",
                        "title": "飞书官网"
                    }
                ]
            }
        }

        mock_client.post.return_value = mock_response

        result = await collector.run({"target": "feishu", "dimension": "features"})

        assert mock_client.post.call_count == 1  # Only search call, no extract
        assert result.success is True
        output = result.output
        assert "content" in output
        assert "飞书完整正文内容 from search" in output["content"]